apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loadbalancer-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadbalancer-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50